import { readSession } from "@/lib/frappe/session";

/**
 * Audit-grade printable wrapper for accounting reports. Mirrors the
 * payroll audit report's print treatment so every finance surface
 * prints the same way:
 *
 *  - a bordered A4/landscape "paper" with the company letterhead
 *  - report title + the period or snapshot date
 *  - "Generated on … by …" line for traceability
 *  - signature block ("Prepared by", "Reviewed by", "Approved by")
 *  - @media print rules that hide app chrome and keep tables intact
 *    across page breaks (thead/tfoot repeat, rows avoid-break)
 *
 * The caller passes the already-rendered report body as `children`
 * (typically a <ReportTable />). Everything else — filter bar, back
 * link, page header — stays outside this component and is marked
 * `print:hidden` by the caller.
 *
 * Server component: reads session cookies for the "Generated by" line.
 */
export function PrintableReport({
  title,
  subtitle,
  company,
  period,
  landscape = true,
  children,
  showSignatures = true,
}: {
  title: string;
  /** Optional one-liner under the title on the printed cover. */
  subtitle?: string;
  /** Legal company name (shows as the letterhead). */
  company: string;
  /** Formatted date range or "As of" line — e.g. "1 Jan 2026 – 10 Mar 2026". */
  period?: string;
  /** A4 landscape by default; set false for narrow reports. */
  landscape?: boolean;
  /** Hide the Prepared/Reviewed/Approved tri-pane (e.g. for ledger exports). */
  showSignatures?: boolean;
  children: React.ReactNode;
}) {
  const session = readSession();
  const generatedAt = new Date();

  return (
    <>
      <article
        className="report-page rounded-xl border bg-white p-6 text-[12.5px] leading-relaxed text-black print:rounded-none print:border-0 print:p-0 print:text-[10.5pt]"
      >
        <header className="mb-5 border-b-2 border-black pb-4 report-avoid-break">
          <div className="flex items-start justify-between gap-6">
            <div>
              <div className="text-[20px] font-extrabold uppercase tracking-wide">
                {company || "Company"}
              </div>
              <div className="mt-1 text-[11px] uppercase tracking-wide text-neutral-500">
                {title}
              </div>
            </div>
            <div className="text-right">
              {period && (
                <div className="text-[14px] font-bold">{period}</div>
              )}
              <div className="mt-1 text-[10px] text-neutral-600">
                Generated {fmtDateTime(generatedAt)}
                {session.fullName
                  ? <> · by {session.fullName}</>
                  : session.userId
                    ? <> · by {session.userId}</>
                    : null}
              </div>
            </div>
          </div>
          {subtitle && (
            <p className="mt-2 text-[11px] text-neutral-600">{subtitle}</p>
          )}
        </header>

        <section>
          {children}
        </section>

        {showSignatures && (
          <section className="mt-10 grid grid-cols-3 gap-10 report-avoid-break report-break-before">
            <Signature label="Prepared by" />
            <Signature label="Reviewed by" />
            <Signature label="Approved by" />
          </section>
        )}
      </article>

      <style>{`
        @media print {
          @page { size: A4 ${landscape ? "landscape" : "portrait"}; margin: 12mm; }
          body * { visibility: hidden; }
          .report-page, .report-page * { visibility: visible; }
          .report-page {
            position: absolute;
            inset: 0;
            width: 100%;
            box-shadow: none;
          }
          .report-avoid-break { break-inside: avoid; page-break-inside: avoid; }
          .report-break-before { break-before: page; page-break-before: always; }
          .report-break-before:first-of-type { break-before: auto; page-break-before: auto; }
          thead { display: table-header-group; }
          tfoot { display: table-footer-group; }
        }
      `}</style>
    </>
  );
}

function Signature({ label }: { label: string }) {
  return (
    <div>
      <div className="h-10 border-b border-black" />
      <div className="mt-1 text-[10px] uppercase tracking-wide text-neutral-500">
        {label}
      </div>
    </div>
  );
}

function fmtDateTime(d: Date): string {
  return d.toLocaleString("en-GB", {
    day: "numeric", month: "short", year: "numeric",
    hour: "2-digit", minute: "2-digit",
  });
}

/** Format a {from, to} range for the printed cover block. */
export function formatPeriod(from: string, to: string): string {
  return `${fmtDate(from)} – ${fmtDate(to)}`;
}

/** Format an "as of" snapshot date for the printed cover block. */
export function formatAsOf(date: string): string {
  return `As of ${fmtDate(date)}`;
}

function fmtDate(iso: string): string {
  if (!iso) return "—";
  const d = new Date(iso);
  if (Number.isNaN(d.valueOf())) return iso;
  return d.toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" });
}
